### ISSUE TITLE
大多数写的比较简短，能在末尾补充深入的URL更好

### ISSUE THREAD

**Issue by elsonwu** [willin/leader.js.cool#1]
RT

**Comment by willin** [comment]
是的, 大多数内容来自于想法的片段或者实际问题中处理的核心代码的片段. 大多数没有花费精力去做详细的演示示例. 

工作的繁忙和压力使得这样简单的事情却略显不那么简单实现.

btw, pr welcome. 欢迎加入自己的理解和详细示例的扩充.

**Comment by elsonwu** [comment]
@willin 了解，这样的总结也是非常好的，支持一下。

**Comment by willin** [comment]
谢谢

**Comment by elsonwu** [comment]
BTW 往后有空能提供补充URL扩展阅读，不用自己写也是很好 :)
